apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/kn5yjf/alkfet_projekt_kn5yjf/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MongoDbSettings__ConnectionString
              value: "mongodb://mongodb:27017"
            - name: MongoDbSettings__DatabaseName
              value: "TodoDb"