name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      BACKEND_IMAGE: ghcr.io/kn5yjf/alkfet_projekt_kn5yjf/backend:latest
      FRONTEND_IMAGE: ghcr.io/kn5yjf/alkfet_projekt_kn5yjf/frontend:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore backend
        run: dotnet restore ./backend/MyApi/MyApi.csproj

      - name: Build backend
        run: dotnet build ./backend/MyApi/MyApi.csproj --configuration Release --no-restore

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

#      - name: Test frontend
#        working-directory: ./frontend
#        run: npm test -- --watch=false

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build backend image
        run: docker build -t $BACKEND_IMAGE ./backend/MyApi

      - name: Build frontend image
        run: docker build -t $FRONTEND_IMAGE ./frontend

      - name: Push backend image
        run: docker push $BACKEND_IMAGE

      - name: Push frontend image
        run: docker push $FRONTEND_IMAGE
